version: '3.3'
services:
  db:
    image: postgres:13.4
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: warp
    volumes:
      - database_folder:/var/lib/postgresql/data
    networks:
      - warp-next_net
  web:
    build: .
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - .env
    environment:
      RAILS_SERVE_STATIC_FILES: "true"
      RAILS_ENV: production
      DATABASE_HOST: db
    restart: always
    ports:
      - "3002:3000"
    networks:
      - warp-next_net
    depends_on:
      - db
    volumes:
      - image_folder:/warp-next/storage/
networks:
  warp-next_net:
volumes:
  database_folder:
    external:
      name: warp-next_db
  image_folder:
    external:
      name: warp-next_images
